package com.xhorse.entity.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "CopyHistory_CopyHistory")
public class XhCopyHistory {
    private String id;

    private String sn;

    private String customerId;

    private String name;

    private String data;

    private String  create_At;

    private Integer copyType;

    private Integer chipType;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "Sn")
    public String getSn() {
        return sn;
    }

    public void setSn(String sn) {
        this.sn = sn;
    }

    @DynamoDBAttribute(attributeName="CustomerId")
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    @DynamoDBAttribute(attributeName="Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    @DynamoDBAttribute(attributeName = "Data")
    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
    @DynamoDBAttribute(attributeName = "Create_At")
    public String getCreate_At() {
        return create_At;
    }

    public void setCreate_At(String create_At) {
        this.create_At = create_At;
    }
    @DynamoDBAttribute(attributeName = "CopyType")
    public Integer getCopyType() {
        return copyType;
    }

    public void setCopyType(Integer copyType) {
        this.copyType = copyType;
    }
    @DynamoDBAttribute(attributeName = "ChipType")
    public Integer getChipType() {
        return chipType;
    }

    public void setChipType(Integer chipType) {
        this.chipType = chipType;
    }
}
